Added OpFlashes and XARAPUCA flashes to SimpleFlash
SBNSoftware/sbnanaobj pull request #107
Opened 2023-08-15 21:38 UTC by Robert-Darby

- Added OpFlashes to SimpleFlash for SBND and ICARUS
- Added XARAPUCA flashes to SimpleFlash for SBND
- - 2/4 flashes/slice in ICARUS/SBND
- - Each slice has seperate training metrics
- SRSlice updated to account for extra slices

2023-08-15 21:51 UTC, Robert-Darby commented
Related PRs:
icaruscode: https://github.com/SBNSoftware/icaruscode/pull/621
sbndcode: https://github.com/SBNSoftware/sbndcode/pull/381
sbncode: https://github.com/SBNSoftware/sbncode/pull/382
sbnanaobj: https://github.com/SBNSoftware/sbnanaobj/pull/107

2023-08-22 17:02 UTC, ikatza requested changes

2023-08-22 17:02 UTC, ikatza commented on sbnanaobj/StandardRecord/SRSlice.h
> +      SRFlashMatch fmatch_a; //!< PMT Simple  flash-match for this slice of TPC charge
I don't think there's any point in keeping the copies.

2023-10-10 16:32 UTC, ikatza approved these changes

2024-01-16 11:22 UTC, merged