Adding offbeam gate counting in CAFs
SBNSoftware/sbnanaobj pull request #79
Opened 2022-09-30 21:48 UTC by jzettle

Added offbeam gate counting in CAFs adding a similar object to what is added for BNB and NuMI spill accounting. Looks at the number of gates for BNB and NuMI offbeam alone for offbeam data which event-by-event is computed as the difference in the number of gates for the previous event.

2022-09-30 21:55 UTC, jzettle commented
This is a set of PRs that spans https://github.com/SBNSoftware/sbnana/pull/89, https://github.com/SBNSoftware/sbncode/pull/298, and https://github.com/SBNSoftware/sbnobj/pull/67

2022-10-13 21:03 UTC, jzennamo commented on sbnanaobj/StandardRecord/SREXTInfo.cxx
> +    isMinBias(false)
These should be commented what they mean or their name should be changed to something more generic.

2022-10-13 21:03 UTC, jzennamo commented on sbnanaobj/StandardRecord/SREXTInfo.h
> +    bool isMinBias;
These should be commented what they mean or their name should be changed to something more generic.

2022-10-19 20:44 UTC, PetrilloAtWork requested changes
Fortunately the integration test caught the error somehow...
This commit is trying to redefine the checksum of `caf::SRHeader` version 17 which was previously there. This must not be, since version 17 was seen in a release and data may have been produced with it.
A new version 18 should be added instead:
```xml
<class name="caf::SRHeader" ClassVersion="18">
  <version ClassVersion="18" checksum="2118058550"/>
  <version ClassVersion="17" checksum="2390355049"/>
```

2023-07-17 18:38 UTC, closed without merging